name: Run Tender Bot

on:
  # Schedule at 6:00 AM GMT+1 (5:00 AM UTC)
  schedule:
   - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install System Dependencies and Browser
        run: |
          # Install all necessary tools for file processing
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr tesseract-ocr-fra tesseract-ocr-ara tesseract-ocr-eng poppler-utils antiword
          
          # Install Chrome browser and matching ChromeDriver
          sudo apt-get install -y wget unzip
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          DRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_STABLE")
          wget -q "https://storage.googleapis.com/chrome-for-testing-public/${DRIVER_VERSION}/linux64/chromedriver-linux64.zip"
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          rm -rf chromedriver-linux64 chromedriver-linux64.zip google-chrome-stable_current_amd64.deb

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tender Bot
        run: python main.py

      - name: Upload summary CSV as artifact
        if: always() # Always run this step to capture the output file
        uses: actions/upload-artifact@v4
        with:
          name: tender-results-summary
          # *** CRITICAL FIX: The python script saves a 'summary' file ***
          path: tender_results_summary.csv
          if-no-files-found: ignore # Don't fail if the script creates no file

      - name: Upload debug files on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-files
          path: |
            error_page_*.png
            error_page_*.html
          if-no-files-found: ignore
